/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hi
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        NameUser1 = new javax.swing.JLabel();
        NameUser2 = new javax.swing.JLabel();
        NameUser3 = new javax.swing.JLabel();
        NameUser4 = new javax.swing.JLabel();
        NameUser5 = new javax.swing.JLabel();
        NameUser6 = new javax.swing.JLabel();
        NameUser7 = new javax.swing.JLabel();
        NameUser8 = new javax.swing.JLabel();
        NameUser9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_product_25px_2.png"))); // NOI18N
        jLabel3.setText("SẢN PHẨM");

        NameUser.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser.setForeground(new java.awt.Color(255, 255, 255));
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_export_25px.png"))); // NOI18N
        NameUser.setText("XUẤT HÀNG");
        NameUser.setToolTipText("");

        NameUser1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser1.setForeground(new java.awt.Color(255, 255, 255));
        NameUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_supplier_25px.png"))); // NOI18N
        NameUser1.setText("NHÀ CUNG CẤP ");
        NameUser1.setToolTipText("");

        NameUser2.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser2.setForeground(new java.awt.Color(255, 255, 255));
        NameUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_import_25px.png"))); // NOI18N
        NameUser2.setText("NHẬP HÀNG");
        NameUser2.setToolTipText("");

        NameUser3.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser3.setForeground(new java.awt.Color(255, 255, 255));
        NameUser3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser3.setText("HI !");
        NameUser3.setToolTipText("");

        NameUser4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser4.setForeground(new java.awt.Color(255, 255, 255));
        NameUser4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_file_25px_2.png"))); // NOI18N
        NameUser4.setText("PHIẾU NHẬP");
        NameUser4.setToolTipText("");

        NameUser5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser5.setForeground(new java.awt.Color(255, 255, 255));
        NameUser5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-warehouse-25.png"))); // NOI18N
        NameUser5.setText("TỒN KHO");
        NameUser5.setToolTipText("");

        NameUser6.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser6.setForeground(new java.awt.Color(255, 255, 255));
        NameUser6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_database_daily_export_25px.png"))); // NOI18N
        NameUser6.setText("PHIẾU XUẤT");
        NameUser6.setToolTipText("");

        NameUser7.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser7.setForeground(new java.awt.Color(255, 255, 255));
        NameUser7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser7.setText("ADMIN");
        NameUser7.setToolTipText("");

        NameUser8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser8.setForeground(new java.awt.Color(255, 255, 255));
        NameUser8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_account_25px.png"))); // NOI18N
        NameUser8.setText("TÀI KHOẢN ");
        NameUser8.setToolTipText("");

        NameUser9.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser9.setForeground(new java.awt.Color(255, 255, 255));
        NameUser9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-settings-25.png"))); // NOI18N
        NameUser9.setText("THỐNG KÊ");
        NameUser9.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(NameUser1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NameUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NameUser9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(NameUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(NameUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(NameUser1)
                .addGap(18, 18, 18)
                .addComponent(NameUser2)
                .addGap(18, 18, 18)
                .addComponent(NameUser4)
                .addGap(18, 18, 18)
                .addComponent(NameUser)
                .addGap(18, 18, 18)
                .addComponent(NameUser6)
                .addGap(18, 18, 18)
                .addComponent(NameUser5)
                .addGap(18, 18, 18)
                .addComponent(NameUser8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameUser9)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(NameUser3)
                    .addContainerGap(539, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(NameUser7)
                    .addContainerGap(493, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 719, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameUser;
    private javax.swing.JLabel NameUser1;
    private javax.swing.JLabel NameUser2;
    private javax.swing.JLabel NameUser3;
    private javax.swing.JLabel NameUser4;
    private javax.swing.JLabel NameUser5;
    private javax.swing.JLabel NameUser6;
    private javax.swing.JLabel NameUser7;
    private javax.swing.JLabel NameUser8;
    private javax.swing.JLabel NameUser9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
